# Generated by Django 2.0.2 on 2018-07-03 20:31

import contabilidade.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competencia', models.DateField(help_text='Digite no formato: dd/mm/aaaa', unique=True)),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('B', 'Bloqueada pela Contabildade')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-data_competencia'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Apenas valores numéricos, de 0 até 9, são permitidos.')], verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição da Conta')),
                ('tipo_conta', models.CharField(choices=[('A', 'Analítica'), ('S', 'Sintética'), ('G', 'Grupo')], max_length=1, verbose_name='Tipo da Conta')),
                ('conta_ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('grau_conta', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Grau da Conta')),
                ('origem', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Origem da Conta')),
                ('natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza da Conta')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('conta_referencial_bacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_BACEN', to='globais.ContaReferencialBacen')),
                ('conta_referencial_dinamica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_Dinamica', to='globais.ContaReferencialDinamica')),
                ('conta_referencial_susep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_Susep', to='globais.ContaReferencialSusep')),
                ('conta_saldo_balanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resultado', to='contabilidade.Conta')),
                ('conta_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Superior', to='contabilidade.Conta')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo_conta'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='MATRIZ', max_length=15, unique=True, verbose_name='Código')),
                ('sigla', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sigla')),
                ('razao_social', models.CharField(max_length=60, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=60, verbose_name='Nome Fantasia')),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='CEP')),
                ('telefone1', models.CharField(default=0, max_length=15, verbose_name='Telefone #1')),
                ('telefone2', models.CharField(default=0, max_length=15, verbose_name='Telefone #2')),
                ('data_processamento', models.DateField(auto_now_add=True, null=True)),
                ('data_competencia', models.DateField(blank=True, null=True, verbose_name='Data de Competência')),
                ('site_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site da Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email da Empresa')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=15, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=15, null=True, verbose_name='Inscrição Municipal')),
                ('tipo_empresa', models.CharField(choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro presumido'), ('LR', 'Lucro Real')], default='LR', max_length=2)),
                ('agrupa_itens_pedido', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('bloqueia_clientes_em_atraso', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('grau_conta', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Grau da Conta Contábil')),
                ('mascara_conta', models.CharField(default='9.9.99.99.999', max_length=15)),
                ('codigo_cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globais.CodigoCnae')),
                ('contador_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contador', to=settings.AUTH_USER_MODEL)),
                ('diretor_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globais.Uf')),
                ('gerente_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(default=2927408, on_delete=django.db.models.deletion.CASCADE, to='globais.Municipio')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_historico', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Código do Histórico')),
                ('descricao', models.CharField(max_length=60)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
            ],
            options={
                'verbose_name': 'Histórico Padrão',
                'verbose_name_plural': 'Históricos Padrões',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Informe valor positivo.', max_digits=16, max_length=16, validators=[contabilidade.models.validate_valor_minimo])),
                ('d_c', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='D/C')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, max_length=16)),
                ('historico', models.CharField(max_length=250, verbose_name='Histórico')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Número do Documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('codigo_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.Historico')),
                ('codigo_participante', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.Participante')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.Conta')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis (Lançamentos)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContabilHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, max_length=16)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, max_length=16)),
                ('data_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.Competencia')),
            ],
            options={
                'verbose_name': 'Movimento Contábil',
                'verbose_name_plural': 'Movimentos Contábeis (Header)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoContaContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(default='D', max_length=1)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('debitos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creditos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.Conta')),
                ('data_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.Competencia')),
            ],
            options={
                'verbose_name': 'Saldo da Conta Contábil',
                'verbose_name_plural': 'Saldos das Contas Contábeis',
                'ordering': ['conta', '-data_competencia'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='CHQ', max_length=3, unique=True)),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimento',
                'verbose_name_plural': 'Tipos de Movimentos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together={('sigla', 'descricao')},
        ),
        migrations.AddField(
            model_name='movimentocontabilheader',
            name='tipo_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidade.TipoMovimento'),
        ),
        migrations.AddField(
            model_name='movimentocontabilheader',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.MovimentoContabilHeader'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidade.TipoDocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together={('codigo_historico', 'descricao')},
        ),
        migrations.AlterUniqueTogether(
            name='saldocontacontabil',
            unique_together={('data_competencia', 'conta')},
        ),
        migrations.AlterUniqueTogether(
            name='conta',
            unique_together={('codigo_conta', 'descricao')},
        ),
    ]
