# Generated by Django 2.0.2 on 2018-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_auto_20180705_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtotributacao',
            name='situacao_tributaria_icms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produtotributacao',
            name='situacao_tributaria_nfce',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produtotributacao',
            name='situacao_tributaria_pis',
            field=models.PositiveIntegerField(),
        ),
    ]
