# Generated by Django 2.0.2 on 2018-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_auto_20180706_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoweb',
            name='modelodocumentofiscal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
