# Generated by Django 2.0.2 on 2018-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_auto_20180706_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoweb',
            name='situacaodocumentosped',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
