# Generated by Django 2.0.2 on 2018-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_auto_20180706_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidowebitem',
            name='centro_custo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidowebitem',
            name='natureza_custos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
