# Generated by Django 2.0.2 on 2018-08-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_auto_20180706_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoweb',
            name='data_pedido',
            field=models.DateField(auto_now_add=True, verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidowebitem',
            name='autorizacao_faturamento',
            field=models.CharField(blank=True, help_text='Número da autorização de faturamento emitida pelo cliente ou pelo fornecedor', max_length=20, null=True, verbose_name='Número da autorização para Faturamento'),
        ),
        migrations.AlterField(
            model_name='pedidowebitem',
            name='observacoes',
            field=models.CharField(blank=True, default=' ', help_text='Observação para efeito de informação fiscal específica neste produto', max_length=40, null=True),
        ),
    ]
