# Generated by Django 2.0.2 on 2018-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0008_auto_20180818_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
