# Generated by Django 2.0.2 on 2018-07-03 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('apelido', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cep', models.IntegerField(blank=True, default=0, null=True)),
                ('bairro', models.CharField(default='Bairro', max_length=30)),
                ('cidade', models.CharField(default='Cidade', max_length=50)),
                ('uf', models.CharField(blank=True, default='BA', max_length=2, null=True)),
                ('nivel_acesso', models.IntegerField(default=0)),
                ('supervisor', models.BooleanField(default=False)),
                ('segunda_feira', models.BooleanField(default=True)),
                ('segunda_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('segunda_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('terca_feira', models.BooleanField(default=True)),
                ('terca_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('terca_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('quarta_feira', models.BooleanField(default=True)),
                ('quarta_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('quarta_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('quinta_feira', models.BooleanField(default=True)),
                ('quinta_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('quinta_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('sexta_feira', models.BooleanField(default=True)),
                ('sexta_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('sexta_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('sabado', models.BooleanField(default=True)),
                ('sabado_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('sabado_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('domingo', models.BooleanField(default=False)),
                ('domingo_hora_inicio', models.TimeField(blank=True, default='8:00', null=True)),
                ('domingo_hora_final', models.TimeField(blank=True, default='17:00', null=True)),
                ('opera_caixa', models.BooleanField(default=False)),
                ('numero_checkout', models.IntegerField(default=0, null=True)),
                ('comprador', models.BooleanField(default=False)),
                ('limite_por_compra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('limite_compra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('funcionario', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Sim', max_length=3)),
                ('vendedor', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Não', max_length=3)),
                ('codigo_supervisor', models.IntegerField(default=0, null=True)),
                ('comissao_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comissao_sobre_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('objetivo_mensal_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('banco_numero', models.IntegerField(default=0, null=True)),
                ('banco_agencia', models.IntegerField(default=0, null=True)),
                ('banco_digito_verficador', models.IntegerField(default=0, null=True)),
                ('data_nascimento', models.DateField(blank=True, default='2009-12-31', null=True)),
                ('regiao_venda', models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Região de Venda')),
                ('departamento', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('matricula', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('identidade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateField(blank=True, default='2009-12-31', null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=10, null=True)),
                ('fisica_juridica', models.CharField(default='F', max_length=1)),
                ('cpf_cnpj', models.IntegerField(default=0)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('ddd_residencia', models.IntegerField(default=0, null=True)),
                ('tel_residencia', models.IntegerField(default=0, null=True)),
                ('ddd_celular', models.IntegerField(default=0, null=True)),
                ('tel_celular', models.IntegerField(default=0, null=True)),
                ('informacoes_adicionais', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('email', models.EmailField(default='usuario@email.com', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'ordering': ('nome',),
            },
        ),
    ]
