# Generated by Django 2.0.2 on 2018-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='centro_custos',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='natureza_custos',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
