# Generated by Django 2.0.2 on 2018-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_auto_20180704_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail'),
        ),
    ]
