# Generated by Django 2.0.2 on 2018-08-18 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faturamento', '0003_auto_20180705_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
