# Generated by Django 2.0.2 on 2018-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_participante_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoparticipante',
            name='ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regiaodevenda',
            name='ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
